### ISSUE TITLE
Allow multiple gitlab hosts

### ISSUE THREAD

**Issue by eRadical** [cinatic/gitlab-extension#4] opened 2020-11-03 16:43 UTC
Hi,

First of all: **awesome extension! Thank you for your work.**

I would like to have the possibility of adding more that one host.

I have an account on gitlab.com but also another account at my employer.

**Comment by cinatic** [comment] 2020-11-09 19:29
duplicate of #2  this will be added in next release

**Closed as completed by cinatic** 2020-11-09 19:29 UTC
Labels: duplicate
